<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsAccounts\Service\AnalyticsService' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Service\\AnalyticsService'] = new \PrestaShop\Module\PsAccounts\Service\AnalyticsService('pEJGnRxw47CU01efFjMyl1S7YcxshLxl', ${($_ = isset($this->services['ps_accounts.logger']) ? $this->services['ps_accounts.logger'] : $this->load('getPsAccounts_LoggerService.php')) && false ?: '_'});
