<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\CustomerDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\CustomerDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\CustomerDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\CustomerRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\CustomerRepository'] : $this->load('getCustomerRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\CustomerDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\CustomerDecorator'] : $this->load('getCustomerDecoratorService.php')) && false ?: '_'});
