<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\CustomProductCarrierDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\CustomProductCarrierDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\CustomProductCarrierDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ProductCarrierRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ProductCarrierRepository'] : $this->load('getProductCarrierRepositoryService.php')) && false ?: '_'});
