<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\ManufacturerDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\ManufacturerDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\ManufacturerDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ManufacturerRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ManufacturerRepository'] : $this->load('getManufacturerRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\ManufacturerDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\ManufacturerDecorator'] : $this->load('getManufacturerDecoratorService.php')) && false ?: '_'});
