<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\ProductSupplierDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\ProductSupplierDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\ProductSupplierDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ProductSupplierRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\ProductSupplierRepository'] : $this->load('getProductSupplierRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\ProductSupplierDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\ProductSupplierDecorator'] : $this->load('getProductSupplierDecoratorService.php')) && false ?: '_'});
