<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\StockDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\StockDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\StockDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StockRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StockRepository'] : $this->load('getStockRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StockMvtRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StockMvtRepository'] : $this->load('getStockMvtRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\StockDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\StockDecorator'] : $this->load('getStockDecoratorService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\ArrayFormatter']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\ArrayFormatter'] : ($this->services['PrestaShop\\Module\\PsEventbus\\Formatter\\ArrayFormatter'] = new \PrestaShop\Module\PsEventbus\Formatter\ArrayFormatter())) && false ?: '_'});
