<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\StoreDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\StoreDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\StoreDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StoreRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\StoreRepository'] : $this->load('getStoreRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\StoreDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\StoreDecorator'] : $this->load('getStoreDecoratorService.php')) && false ?: '_'});
