<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Service\SpecificPriceService' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Service\\SpecificPriceService'] = new \PrestaShop\Module\PsEventbus\Service\SpecificPriceService(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\SpecificPriceRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\SpecificPriceRepository'] : $this->load('getSpecificPriceRepositoryService.php')) && false ?: '_'});
