<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsEventbus\Provider\SupplierDataProvider' shared service.

return $this->services['PrestaShop\\Module\\PsEventbus\\Provider\\SupplierDataProvider'] = new \PrestaShop\Module\PsEventbus\Provider\SupplierDataProvider(${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Repository\\SupplierRepository']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Repository\\SupplierRepository'] : $this->load('getSupplierRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\SupplierDecorator']) ? $this->services['PrestaShop\\Module\\PsEventbus\\Decorator\\SupplierDecorator'] : $this->load('getSupplierDecoratorService.php')) && false ?: '_'});
