<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdelcya\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdelcya/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNdelcya.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNdelcya\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNdelcya\appProdProjectContainer([
    'container.build_hash' => 'Ndelcya',
    'container.build_id' => '3a94747f',
    'container.build_time' => 1701474710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdelcya');
