<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerId1jvtf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerId1jvtf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerId1jvtf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerId1jvtf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerId1jvtf\appProdProjectContainer([
    'container.build_hash' => 'Id1jvtf',
    'container.build_id' => '26ca2b97',
    'container.build_time' => 1701031300,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerId1jvtf');
