version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop-database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    volumes:
      - ./database:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:80
      - 443:443
    environment:
      PS_FOLDER_ADMIN: admin123
      PS_FOLDER_INSTALL: install123
      PS_DEV_MODE: 1
    volumes:
      - ./src:/var/www/html
    networks:
      - prestashop_network
networks:
    prestashop_network:
